
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mi_proyecto_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'mi_proyecto_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  mi_proyecto_dbt:
    example:
      +enabled: false  # ignore todo dentro de esta carpeta

    # Configuración para la carpeta models/staging/
    staging:
      +schema: staging
      +materialized: view  # Generalmente staging son vistas

    # Configuración para la carpeta models/intermediate/
    intermediate:
      +schema: intermediate
      +materialized: view  # Generalmente intermediate son vistas

    # Configuración para la carpeta models/marts/
    marts:
      +schema: marts
      +materialized: table # Los marts suelen ser tablas físicas